updates

diff --git a/makepass b/makepass
--- a/makepass
+++ b/makepass
@@ -1,54 +1,83 @@
 #!/bin/bash
 
-# makepass:  Generates a password of custom length
-# Requires:  'head' binary from coreutils
-# Version:   0.1
-# Build:     20-Nov-2010
-# Author:    Heiko Barth
-# Licence:   Beer-Ware (See: http://en.wikipedia.org/wiki/Beerware)
+# Makepass: Generate passwords with the power of "tr"
+# Version:  0.1
+# Build:    2019-10-31
+# Author:   Heiko Barth
+# Licence:  Beer-Ware (See: http://en.wikipedia.org/wiki/Beerware)
 
-# Character classes
-CHARS=$CHARS'abcdefghijkmnpqrstuvwxyz'	# lower case; 'l' 'o' removed
-CHARS=$CHARS'ABCDEFGHJKLMNPQRSTUVWXYZ'	# upper case; 'I' 'O' removed
-CHARS=$CHARS'123456789'			# digits; 0 removed
-CHARS=$CHARS'!$%#&(){}=?'		# some special chars
+APP=${0##*/}
+VER=0.1
+RNG=/dev/random
 
-# Random Number Generator
-RNG='/dev/random'
+CHARSET=${1:-[:alnum:]}	# default to 'all letters and digits'
+COUNT=${2:-20}		# default to 20
 
-GREEN='\e[1;32m'  # Light Green
-YELLOW='\e[1;33m' # Light Yellow
-RST='\e[0m'
+if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+        {
+		read -d '' CHARSETS <<-"EOF"
+			[:alnum:]
+			all letters and digits
 
-# Some input validation
-if [[ $1 =~ ^[0-9]+$ ]] && [ $1 -gt 0 ]; then length=$1
-	# Check if custom characters are given
-	if [ $# -eq 2 ] && [ ${#2} -gt 0 ]; then
-		shift
-		CHARS=$@
-		echo -e "${YELLOW}Using custom characters: $CHARS$RST"
-	fi
-	
-	tput sc
-	echo -n -e "${YELLOW}Progress: 0 of $length characters$RST"
-	
-	# Get random characters
-	while [ 1 ]; do
-		c=$(head -c 1 $RNG)
-		if [[ $c =~ [$CHARS] ]]; then
-			res=$res$c
-			let i++
-			tput el1; tput rc
-			echo -n -e "${YELLOW}Progress: $i of $length characters$RST"
-			if [ ${#res} -eq $length ]; then
-				tput el1; tput rc
-				echo -e "${GREEN}Password: $res\n$RST"
-				exit
-			fi
-		fi
-	done
-else
-	echo "Syntax: makepass <length> [<characters>]" >&2
-	echo >&2
-	exit 1
+			[:alpha:]
+			all letters
+
+			[:blank:]
+			all horizontal whitespace
+
+			[:cntrl:]
+			all control characters
+
+			[:digit:]
+			all digits
+
+			[:graph:]
+			all printable characters, not including space
+
+			[:lower:]
+			all lower case letters
+
+			[:print:]
+			all printable characters, including space
+
+			[:punct:]
+			all punctuation characters
+
+			[:space:]
+			all horizontal or vertical whitespace
+
+			[:upper:]
+			all upper case letters
+
+			[:xdigit:]
+			all hexadecimal digits
+		EOF
+		echo "$APP $VER"
+	        echo
+        	echo "Syntax: $APP [<character set>] [<count>]"
+	        echo
+	        echo "Predefined character sets:"
+        	echo
+	        echo "$CHARSETS" | column -e
+	} >&2
+        exit 1
 fi
+
+checkBinarys() {
+        for i in "$@"; do
+                hash "$i" 2>/dev/null || {
+                        echo "Binary missing: $i" >&2
+                        echo >&2
+                        exit 1
+                }
+        done
+}
+checkBinarys "head" "tr"
+
+echo -n "Password: "
+for ((i=1; i<=COUNT; i++)); do
+	echo -n "$(tr -dc "$CHARSET" < $RNG | head -c 1)"
+done
+
+echo
+echo
