update tcp-wait

diff --git a/tcp-wait b/tcp-wait
--- a/tcp-wait
+++ b/tcp-wait
@@ -1,27 +1,41 @@
 #!/bin/bash
 
-if [ $# -lt 2 ]; then
-	echo "Wait until destination port is open." >&2
-	echo >&2
-	echo "Usage: $(basename "$0") <host> <port> [<retry>]" >&2
-	echo >&2
-	echo "host	destination host" >&2
-	echo "port	destination tcp port" >&2
-	echo "retry	wait n seconds before retry (default is 1)" >&2
-	echo >&2
+set -ueo pipefail
+
+trapCtrlC() {
+	echo
+	echo "Aborting.."
+	echo
 	exit 1
-fi
+}
 
-if [ -z "$3" ]; then
-	WAIT=1
-else
-	WAIT=$3
-fi
+trap trapCtrlC SIGINT   # Catch CTRL-C
 
-echo -n "Connecting to ($1:$2)"
-#while !(nmap -P0 -p$2 $1 2> /dev/null | grep -q open ); do
-while !(nc -z -w 1 "$1" "$2" 2> /dev/null ); do
-	echo -n "."
-	sleep $WAIT
+if [ $# -lt 2 ]; then
+	APP=${0##*/}
+	echo "Wait for a TCP port to be available."
+	echo
+	echo "Syntax: $APP <host> <port> [<timeout> <delay>]"
+	echo
+	exit 1
+fi >&2
+
+# 1 second default
+TIMEOUT=${3:-1}
+DELAY=${4:-1}
+
+echo "Host:    $1"
+echo "Port:    $2"
+echo "Timeout: $TIMEOUT"
+echo "Delay:   $DELAY"
+echo
+
+# inspired from: https://github.com/hassio-addons/bashio/blob/master/lib/net.sh
+until (timeout "$TIMEOUT" bash -c "< /dev/tcp/$1/$2") &> /dev/null; do
+	echo -n .
+	sleep "$DELAY"
 done
-echo -e " \e[0;32mOK\e[0m"
+
+echo
+echo ">> $1:$2 connected."
+echo
